  version: 2.1
  jobs:
    build:
      docker: 
        - image: arminous/mosze:build
      steps:
        - checkout 
        - run:
            name: "Build"
            command: make -f makefile
        - persist_to_workspace:
            root: ~/project
            paths:
              - terminal
              - input
              - outputTest
              - filesystem.json
    
    cppcheck:
      docker:
        - image: arminous/mosze:analysis
      steps:
        - checkout
        - run:
            name: cppcheck
            command: cppcheck --language=c++ --enable=performance --error-exitcode=420 *.cpp *.h
            
    valgrind:        
      docker:
        - image: arminous/mosze:analysis
      steps:
        - attach_workspace:
            at: ~/project

        - run:
            name: valgrind
            command: valgrind --leak-check=full ./terminal filesystem.json < input
            
    doxygen:
      docker:
        - image: arminous/mosze:doxygen
      steps:
        - checkout
        - run: doxygen Doxyfile && rm -rf Docs && mkdir Docs && mv Doxygen/html/* Docs/ &&  git add . && git config user.email kertesz.armin96@gmail.com && git config user.name kearmin && git stash && git checkout gh-pages && git merge --squash --strategy-option=theirs stash && git commit -m "build page [skip ci]" && git push origin gh-pages
            
    output:
      machine:
        image: ubuntu-1604:201903-01
      steps:
        - attach_workspace:
            at: ~/project      
        - run:
            name: Output
            command: ./terminal filesystem.json < input
    test:
      docker:
        - image: scony/googletest:latest
      steps:
        - checkout
        - run: cd test && cmake CMakeLists.txt && make && ./executeTests
    diff:
      machine:
        image: ubuntu-1604:201903-01
      steps:
        - attach_workspace:
            at: ~/project        
        - run:
            name: Diff
            command: ./terminal filesystem.json < input > output && diff output outputTest
            
  workflows:
    version: 2
    build_print_diff:
      jobs:
        - build
        - test
        - cppcheck
        - doxygen
        - valgrind:
           requires:
             - build
        - output:
           requires:
             - build
        - diff:
           requires:
             - build
