  version: 2.1
  jobs:
    build:
      docker: 
        - image: arminous/mosze:test
      steps:
        - checkout 
        - run:
            name: "Build"
            command: make -f makefile
        - persist_to_workspace:
            root: ~/project
            paths:
              - terminal
              - input
              - outputTest
              - filesystem.json
    
    cppcheck:
      docker:
        - image: arminous/mosze:analysis
      steps:
        - checkout
        - run:
            name: cppcheck
            command: cppcheck --enable=performance --error-exitcode=420 *.cpp *.h
            
    valgrind:        
      docker:
        - image: arminous/mosze:analysis
      steps:
        - attach_workspace:
            at: ~/project

        - run:
            name: valgrind
            command: valgrind --leak-check=full ./terminal filesystem.json < input
            
    output:
      machine:
        image: ubuntu-1604:201903-01
      steps:
        - attach_workspace:
            at: ~/project      
        - run:
            name: Output
            command: ./terminal filesystem.json < input

    diff:
      machine:
        image: ubuntu-1604:201903-01
      steps:
        - attach_workspace:
            at: ~/project        
        - run:
            name: Diff
            command: ./terminal filesystem.json < input > output && diff output outputTest
            
  workflows:
    version: 2
    build_print_diff:
      jobs:
        - build
        - cppcheck
        - valgrind:
           requires:
             - build
        - output:
           requires:
             - build
        - diff:
           requires:
             - build
