FROM debian
RUN apt-get update && apt-get install -y\
    git\
    doxygen\
    texlive\
    texlive-latex-extra\
    texlive-lang-european\
    texlive-lang-cyrillic\
    make\
    && apt-get autoclean
